import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
    overlay: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0,0,0,0.6)',
    },
    sheetContainer: {
        backgroundColor: '#f9fafb',
        width: '100%',
        height: '83%',
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        overflow: 'hidden',
    },

    // Header
    header: {
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: 'white',
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    avatar: {
        height: 44,
        width: 44,
        backgroundColor: '#f3f4f6',
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarText: {
        fontSize: 18,
        fontWeight: '800',
        color: '#374151',
    },
    customerName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#111827',
    },
    customerPhone: {
        fontSize: 13,
        color: '#6b7280',
        marginTop: 2,
    },
    closeButton: {
        padding: 10,
        backgroundColor: '#f9fafb',
        borderRadius: 99,
    },

    // Content
    content: {
        flex: 1,
        paddingHorizontal: 24,
        paddingTop: 24,
        backgroundColor: '#ffffff',
    },

    // Sections
    section: {
        marginBottom: 24,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 16,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#111827',
        marginBottom: 14,
    },
    loadingContainer: {
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    loadingText: {
        fontSize: 14,
        color: '#9ca3af',
        fontWeight: '500',
    },
    addTaskHeaderButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: '#9f95f2',
        paddingVertical: 8,
        paddingHorizontal: 14,
        borderRadius: 10,
    },
    addTaskHeaderButtonText: {
        fontSize: 13,
        fontWeight: '700',
        color: '#ffffff',

    },
    listContainer: {
        gap: 8,
        paddingBottom: 12,
    },

    // Compact Deal Card
    compactCard: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 14,
        gap: 14,

    },
    compactImg: {
        width: 44,
        height: 44,
        borderRadius: 10,
        backgroundColor: '#f3f4f6',
    },
    compactTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#111827',
    },
    compactSub: {
        fontSize: 12,
        color: '#4f46e5',
        fontWeight: '600',
        marginTop: 2,
    },

    // Task Card
    taskCard: {
        padding: 14,
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 12,
    },
    taskHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        //marginBottom: 10,
    },
    taskTypeBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 6,
    },
    taskTypeText: {
        fontSize: 10,
        fontWeight: 'bold',
        textTransform: 'uppercase',
        letterSpacing: 0.5,

    },
    statusBadge: {
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 5,
    },
    statusText: {
        fontSize: 9,
        fontWeight: 'bold',
        color: 'white',
        textTransform: 'uppercase',
    },
    taskNote: {
        fontSize: 13,
        color: '#374151',
        marginBottom: 10,
        lineHeight: 18,
    },
    taskFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderTopWidth: 1,
        borderTopColor: '#f3f4f6',
        paddingTop: 10,
        gap: 10,
    },
    taskDate: {
        fontSize: 11,
        color: '#6b7280',
        fontWeight: '600',
    },
    taskProperty: {
        fontSize: 11,
        color: '#9ca3af',
        marginTop: 3,
    },
    taskSiteVisitButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: '#9f95f2',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 8,
        flexShrink: 0,
    },
    taskSiteVisitButtonText: {
        fontSize: 11,
        fontWeight: '700',
        color: 'white',
    },
    emptyTasksContainer: {
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyTasksText: {
        fontSize: 13,
        color: '#9ca3af',
        textAlign: 'center',
    },

    // Match Card
    matchCard: {
        flexDirection: 'row',
        padding: 16,
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 16,
        gap: 16,

    },
    pendingCard: {
        flexDirection: 'row',
        padding: 16,
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 16,
        gap: 16,
    },
    pendingCardVertical: {
        flexDirection: 'column',
        padding: 16,
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 16,
        gap: 12,
    },
    pendingCardWithButtons: {
        flexDirection: 'column',
        padding: 16,
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 16,
        gap: 12,
    },
    pendingCardTop: {
        flexDirection: 'row',
        gap: 16,
    },
    pendingCardImage: {
        width: '100%',
        height: 180,
        borderRadius: 12,
        backgroundColor: '#f3f4f6',
    },
    pendingCardContent: {
        gap: 8,
    },
    matchImg: {
        width: 70,
        height: 70,
        borderRadius: 12,
        backgroundColor: '#f3f4f6',
    },
    matchContent: {
        flex: 1,
        justifyContent: 'space-between',
        paddingVertical: 2,
    },
    matchTitle: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#111827',
        marginBottom: 2,
    },
    matchLoc: {
        fontSize: 12,
        color: '#6b7280',
        marginLeft: 4,
    },
    rowCenter: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    matchFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 4,
    },
    matchPrice: {
        fontSize: 15,
        fontWeight: '900',
        color: '#6b7280',
    },
    pendingActionButtons: {
        flexDirection: 'row',
        gap: 8,
        marginTop: 12,
    },
    pendingActionButtonsVertical: {
        flexDirection: 'row',
        gap: 10,
        width: '100%',
    },
    interestedActionBtn: {
        flex: 1,
        backgroundColor: '#34d399',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 10,
        alignItems: 'center',
    },
    interestedActionBtnFull: {
        width: '100%',
        backgroundColor: '#34d399',
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderRadius: 10,
        alignItems: 'center',
    },
    interestedActionText: {
        color: 'white',
        fontSize: 13,
        fontWeight: '700',
    },
    visitActionBtn: {
        flex: 1,
        backgroundColor: '#1f2937',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 10,
        alignItems: 'center',
    },
    visitActionText: {
        color: 'white',
        fontSize: 13,
        fontWeight: '700',
    },
    startDealActionBtn: {
        flex: 1,
        backgroundColor: '#1f2937',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 10,
        alignItems: 'center',
    },
    startDealActionText: {
        color: 'white',
        fontSize: 13,
        fontWeight: '700',
    },
    smallDealBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: '#111827',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 8,
    },
    smallDealText: {
        color: 'white',
        fontSize: 11,
        fontWeight: 'bold',
    },
    visitBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        backgroundColor: '#111827',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 8,
    },
    visitBtnText: {
        color: 'white',
        fontSize: 11,
        fontWeight: 'bold',
    },
    dealStartedBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: '#d1fae5',
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderRadius: 8,
    },
    dealStartedText: {
        color: '#059669',
        fontSize: 10,
        fontWeight: 'bold',
    },
    holdBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: '#fef3c7',
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderRadius: 8,
    },
    holdBadgeText: {
        color: '#d97706',
        fontSize: 10,
        fontWeight: 'bold',
    },
    holdBadgeSmall: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
        backgroundColor: '#fef3c7',
        paddingVertical: 3,
        paddingHorizontal: 6,
        borderRadius: 6,
    },
    holdBadgeSmallText: {
        color: '#d97706',
        fontSize: 9,
        fontWeight: 'bold',
    },
    emptyState: {
        padding: 24,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderStyle: 'dashed',
        borderRadius: 16,
        backgroundColor: '#f9fafb',
    },
    emptyText: {
        fontSize: 13,
        color: '#9ca3af',
    },

    // Property Picker
    pickerOverlay: {
        position: 'absolute',
        top: 0, left: 0, right: 0, bottom: 0,
        backgroundColor: 'white',
        zIndex: 50,
    },
    pickerHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 14,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        marginTop: 0,
        backgroundColor: '#ffffff',
    },
    pickerTitle: {
        fontSize: 17,
        fontWeight: '800',
        color: '#6b7280',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginLeft: 6,
    },
    searchContainer: {
        marginTop: 20,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 16,
        marginHorizontal: 20,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        gap: 10,
    },
    searchInput: {
        flex: 1,
        fontSize: 15,
        color: '#111827',
        padding: 0,
    },
    pickerContent: { padding: 20, paddingTop: 8 },
    pickerItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 14,
        marginBottom: 12,
        gap: 14,
    },
    pickerImg: {
        width: 48,
        height: 48,
        borderRadius: 10,
        backgroundColor: '#f3f4f6',
    },
    pickerItemTitle: { fontSize: 14, fontWeight: 'bold' },
    pickerItemLocation: { fontSize: 11, color: '#9ca3af', marginLeft: 4 },
    pickerItemPrice: { fontSize: 13, color: '#6b7280', marginTop: 4 },

    // Stage Indicator
    stageContainer: {
        backgroundColor: 'white',
        paddingVertical: 20,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
    },
    stageScrollContent: {
        paddingHorizontal: 8,
        gap: 24,
    },
    stageItem: {
        alignItems: 'center',
        minWidth: 70,
    },
    stageCircle: {
        width: 56,
        height: 56,
        borderRadius: 28,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 8,
    },
    stageCircleCompleted: { backgroundColor: '#86efac' },
    stageCircleCurrent: { backgroundColor: '#1f2937' },
    stageCircleFuture: { backgroundColor: '#f3f4f6' },
    stageLabel: {
        fontSize: 11,
        fontWeight: '600',
        color: '#9ca3af',
        textAlign: 'center',
    },
    stageLabelActive: { color: '#1f2937', fontWeight: '700' },
    stageUnderline: {
        width: 32,
        height: 3,
        backgroundColor: '#1f2937',
        borderRadius: 2,
        marginTop: 4,
    },

    // --- UPDATED NEXT STEP CARD ---
    nextStepCard: {
        backgroundColor: '#E9E6F7', // Reference Card BG
        borderColor: '#BFB7FD',     // Reference Card Border
        borderWidth: 1,
        borderRadius: 24,
        padding: 20,
        marginBottom: 24,
        // Column layout (default in RN) ensures vertical stacking
        shadowColor: '#BFB7FD',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 3,
    },
    nextStepInfo: {
        marginBottom: 16, // Space between Text and Button
    },
    nextStepLabel: {
        fontSize: 10,
        fontWeight: '800',
        color: '#7c3aed',
        letterSpacing: 1,
        textTransform: 'uppercase',
        marginBottom: 4,
    },
    nextStepTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1f2937',
        marginBottom: 2,
    },
    nextStepSub: {
        fontSize: 12,
        color: '#6b7280',
    },
    proceedButton: {
        backgroundColor: '#9f95f2', // Darker purple when enabled
        paddingVertical: 14,
        borderRadius: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        width: '100%', // Full Width
        shadowColor: '#9f95f2',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 2,
    },
    proceedButtonDisabled: {
        backgroundColor: '#BFB7FD', // Light purple when disabled
        shadowColor: '#BFB7FD',
        opacity: 0.6,
    },
    proceedButtonText: {
        fontSize: 14,
        fontWeight: '700',
        color: 'white', // White Text
    },

    // Customer Contact Card Styles
    contactCard: {
        backgroundColor: 'white',
        borderRadius: 14,
        padding: 16,
        borderWidth: 1,
        borderColor: '#e5e7eb',

    },
    contactInfoSection: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 14,
        gap: 12,
    },
    contactAvatar: {
        width: 46,
        height: 46,
        backgroundColor: '#f3f4f6',
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    contactAvatarText: {
        fontSize: 20,
        fontWeight: '800',
        color: '#6b7280',
    },
    contactDetails: {
        flex: 1,
    },
    contactName: {
        fontSize: 16,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 3,
    },
    contactPhone: {
        fontSize: 14,
        color: '#6b7280',
        fontWeight: '500',
    },
    contactButtonRow: {
        flexDirection: 'row',
        gap: 10,
    },
    contactActionBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        paddingVertical: 10,
        backgroundColor: '#ffffff',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    contactActionText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#374151',
    },

    // Select Properties Styles
    formLabel: {
        fontSize: 13,
        fontWeight: '600',
        color: '#6b7280',
        marginBottom: 8,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    selectedCount: {
        fontSize: 13,
        fontWeight: '600',
        color: '#6366f1',
    },
    selectPropertiesButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: '#ffffff',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#e1e3e6',
        borderStyle: 'dashed',
        marginBottom: 12,
    },
    selectPropertiesButtonText: {
        fontSize: 15,
        fontWeight: '700',
        color: '#6a7380',
    },
    selectedPropertyItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 14,
        gap: 14,

    },
    removeButton: {
        padding: 6,
        backgroundColor: '#fee2e2',
        borderRadius: 8,
    },
    selectablePropertyCard: {
        flexDirection: 'row',
        padding: 16,
        backgroundColor: 'white',
        borderWidth: 2,
        borderColor: '#e5e7eb',
        borderRadius: 16,
        gap: 16,
        shadowColor: '#000',

    },
    selectedPropertyCard: {
        borderColor: '#a78bfa',
        backgroundColor: '#f3f0ff',
    },
    pickerItemSelected: {
        backgroundColor: '#f3f0ff',
        borderColor: '#a78bfa',
    },
    pickerFooter: {
        padding: 20,
        borderTopWidth: 1,
        borderTopColor: '#f3f4f6',
        backgroundColor: 'white',
    },
    doneButton: {
        backgroundColor: '#a78bfa',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 12,
        alignItems: 'center',
    },
    doneButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: 'white',
    },
    checkboxCircle: {
        width: 28,
        height: 28,
        borderRadius: 14,
        borderWidth: 2,
        borderColor: '#d1d5db',
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
    },
    checkboxCircleSelected: {
        backgroundColor: '#a78bfa',
        borderColor: '#a78bfa',
    },

    // Fixed Bottom Button
    fixedBottomContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'white',
        paddingHorizontal: 20,
        paddingVertical: 10,
        paddingBottom: 10,
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
        shadowColor: '#000',


    },
    visitSitesButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 15,
        backgroundColor: '#9f95f2',
        paddingVertical: 16,
        borderRadius: 14,
        shadowColor: '#9f95f2',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 2,
    },
    visitSitesButtonDisabled: {
        backgroundColor: '#bfb7fd',
        shadowColor: '#bfb7fd',
        opacity: 0.6,
    },
    visitSitesButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: 'white',
    },
    twoButtonRow: {
        flexDirection: 'row',
        gap: 10,
        width: '100%',
    },
    halfWidthButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 16,
        borderRadius: 14,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 2,
    },
    interestedButton: {
        backgroundColor: '#34d399',
        shadowColor: '#34d399',
    },
    pendingDecisionButton: {
        backgroundColor: '#1f2937',
        shadowColor: '#1f2937',
    },

    // Map View Styles
    mapViewContainer: {
        flex: 1,
        backgroundColor: '#f9fafb',
    },
    mapImage: {
        width: '100%',
        height: '100%',
        position: 'absolute',
        top: 0,
    },
    mapHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: Platform.OS === 'ios' ? 60 : 50,
        paddingBottom: 16,
        backgroundColor: 'transparent',
    },
    mapHeaderContent: {
        flex: 1,
    },
    mapHeaderTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 2,
    },
    mapHeaderSubtitle: {
        fontSize: 14,
        color: '#6b7280',
    },
    mapCloseButton: {
        width: 40,
        height: 40,
        backgroundColor: 'white',
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    collapsedModalCard: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'white',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        padding: 20,
        paddingBottom: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 10,
    },
    propertiesScrollContent: {
        paddingHorizontal: 4,
        gap: 12,
    },
    propertyScrollCard: {
        width: 300,
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 14,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        borderWidth: 2,
        borderColor: '#e5e7eb',
        marginHorizontal: 6,
    },
    propertyScrollImageSmall: {
        width: 70,
        height: 70,
        borderRadius: 12,
        backgroundColor: '#f3f4f6',
    },
    propertyScrollInfo: {
        flex: 1,
        gap: 6,
    },
    propertyScrollTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#111827',
    },
    propertyScrollLocation: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    propertyScrollLocationText: {
        fontSize: 12,
        color: '#6b7280',
        flex: 1,
    },

    // Expanded Modal Card
    expandedModalCard: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'white',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        padding: 20,
        paddingBottom: 30,

    },
    backButton: {
        position: 'absolute',
        top: 20,
        left: 20,
        width: 36,
        height: 36,
        backgroundColor: '#f3f4f6',
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10,
    },
    handleBar: {
        width: 70,
        height: 5,
        backgroundColor: '#d1d5db',
        borderRadius: 2,
        alignSelf: 'center',
        marginBottom: 12,
    },
    propertiesToShowLabel: {
        fontSize: 20,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 23,
        textAlign: 'center',
    },
    scrollWrapper: {
        marginBottom: 20,
    },
    expandedPropertiesContainer: {
        marginBottom: 28,
    },
    expandedPropertiesScroll: {
        paddingHorizontal: 0,
        gap: 10,
        marginBottom: 20,
    },
    expandedPropertyCard: {
        width: 310,
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 12,
        flexDirection: 'row',
        gap: 10,
        borderWidth: 2,
        borderColor: '#e5e7eb',
        marginHorizontal: 6,
    },
    expandedPropertyCardActive: {
        borderColor: '#bfb7fd',
        backgroundColor: '#faf9ff',
    },
    expandedPropertyCardImage: {
        width: 70,
        height: 70,
        borderRadius: 12,
        backgroundColor: '#f3f4f6',
    },
    expandedPropertyCardInfo: {
        flex: 1,
        justifyContent: 'center',
        gap: 2,
    },
    propertyCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 8,
    },
    expandedPropertyCardTitle: {
        fontFamily: 'Lato_700Bold',
        fontSize: 16,
        fontWeight: '700',
        color: '#111827',
        flex: 1,
    },
    expandedPropertyCardLocation: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    expandedPropertyCardLocationText: {
        fontSize: 13,
        color: '#313131',
        flex: 1,
    },
    feedbackButtonsRow: {
        flexDirection: 'row',
        backgroundColor: 'white',
        borderRadius: 13,
        borderWidth: 1.5,
        borderColor: '#e5e7eb',
        overflow: 'hidden',
        marginBottom: 16,
        alignItems: 'center',
    },
    feedbackBtn: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        paddingVertical: 18,
    },
    verticalDivider: {
        width: 1.5,
        height: '60%',
        backgroundColor: '#e5e7eb',
    },
    feedbackTextHorizontal: {
        fontSize: 12,
        fontWeight: '600',
        color: '#374151',
    },
    contactOwnerButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: 'white',
        paddingVertical: 14,
        borderRadius: 12,
        marginBottom: 12,
        borderWidth: 1.5,
        borderColor: '#d1d5db',
    },
    contactOwnerText: {
        fontSize: 15,
        fontWeight: '700',
        color: '#374151',
    },
    navigateButtonExpanded: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#a9a0f5',
        paddingVertical: 16,
        borderRadius: 14,

    },
    navigateButtonExpandedText: {
        fontSize: 16,
        fontWeight: '700',
        color: 'white',
    },
});

export default styles;
