import { StyleSheet, Platform, StatusBar } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ffffff',
    },
    header: {
        paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight ?? 24) + 16 : 64,
        paddingHorizontal: 20,
        paddingBottom: 16,
        backgroundColor: '#ffffff',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    profileSection: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    profileImage: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#f3f4f6',
    },
    profileAvatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        alignItems: 'center',
        justifyContent: 'center',
    },
    profileAvatarText: {
        fontSize: 18,
        fontWeight: '700',
    },
    profileName: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1f2937',
    },
    closeButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#f3f4f6',
        alignItems: 'center',
        justifyContent: 'center',
    },
    scrollView: {
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 100,
    },
    // Tabs
    tabsContainer: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 30,
        marginTop: 20,
    },
    tab: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 10,
        backgroundColor: '#F4F7FE',
        alignItems: 'center',
        justifyContent: 'center',
    },
    activeTab: {
        backgroundColor: '#000000',
    },
    tabText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#6b7280',
    },
    activeTabText: {
        color: '#ffffff',
    },
    // Property Card
    propertyCard: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        padding: 12,
        marginBottom: 26,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        position: 'relative',
    },
    propertyImage: {
        width: 60,
        height: 60,
        borderRadius: 10,
        backgroundColor: '#f3f4f6',
    },
    propertyInfo: {
        flex: 1,
        marginLeft: 12,
    },
    propertyTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1f2937',
        marginBottom: 3,
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
        marginBottom: 4,
    },
    locationText: {
        fontSize: 12,
        color: '#6b7280',
    },
    propertyPrice: {
        fontSize: 14,
        fontWeight: '700',
        color: '#1f2937',
    },
    dealBadge: {
        position: 'absolute',
        bottom: 10,
        right: 10,
        backgroundColor: '#000000',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 6,
    },
    dealBadgeText: {
        fontSize: 10,
        fontWeight: '700',
        color: '#ffffff',
        letterSpacing: 0.5,
    },
    // Schedule
    scheduleHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 26,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1f2937',
        left: 10,
    },
    addButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: '#BFB7FD',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#9A8CFC',
    },
    addButtonText: {
        fontSize: 13,
        fontWeight: '400',
        color: '#ffffff',
    },
    // Schedule List
    scheduleList: {
        gap: 12,
        marginBottom: 24,
    },
    scheduleItem: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    completedItem: {
        backgroundColor: '#f9fafb',
    },
    scheduleContent: {
        flex: 1,
    },
    scheduleTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1f2937',
        marginBottom: 4,
    },
    completedText: {
        color: '#6b7280',
    },
    scheduleTime: {
        fontSize: 13,
        color: '#9ca3af',
    },
    statusBadgeContainer: {
        alignItems: 'flex-end',
        gap: 8,
    },
    upcomingBadge: {
        backgroundColor: '#fef3c7',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 8,
    },
    upcomingText: {
        fontSize: 11,
        fontWeight: '600',
        color: '#d97706',
    },
    markDoneButton: {
        paddingVertical: 2,
    },
    markDoneText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#6b7280',
        textDecorationLine: 'underline',
    },
    // Reminder - Fixed at bottom
    reminderCardFixed: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#ffffff',
    },
    reminderCardInner: {
        margin: 16,
        backgroundColor: '#ffffff',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    reminderTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1f2937',
        marginBottom: 4,
    },
    reminderSubtitle: {
        fontSize: 13,
        color: '#9ca3af',
    },
    // Empty State
    emptySchedule: {
        alignItems: 'center',
        paddingVertical: 40,
    },
    emptyText: {
        marginTop: 12,
        fontSize: 14,
        color: '#9ca3af',
    },
    // Modal
    modalOverlay: {
        flex: 1,
        justifyContent: 'flex-end',
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        backgroundColor: '#ffffff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingBottom: Platform.OS === 'ios' ? 40 : 20,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#1f2937',
    },
    modalBody: {
        padding: 20,
    },
    inputGroup: {
        marginBottom: 20,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 8,
    },
    input: {
        backgroundColor: '#f9fafb',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 12,
        padding: 14,
        fontSize: 15,
        color: '#1f2937',
    },
    dateTimeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: '#f9fafb',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 12,
        padding: 14,
        marginBottom: 10,
    },
    dateTimeText: {
        fontSize: 15,
        color: '#1f2937',
        fontWeight: '500',
    },
    saveButton: {
        backgroundColor: '#9A8CFC',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        marginTop: 10,
    },
    saveButtonDisabled: {
        backgroundColor: '#d1d5db',
    },
    saveButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#ffffff',
    },
    // Custom Alert Styles
    customAlertOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    customAlertContainer: {
        backgroundColor: '#ffffff',
        borderRadius: 24,
        padding: 28,
        width: '100%',
        maxWidth: 380,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 10,
    },
    reminderAlertContainer: {
        paddingTop: 24,
        paddingBottom: 24,
    },
    customAlertIconContainer: {
        marginBottom: 20,
    },
    customAlertSuccessIcon: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#d1fae5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    customAlertWarningIcon: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#fef3c7',
        alignItems: 'center',
        justifyContent: 'center',
    },
    customAlertTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: '#1f2937',
        marginBottom: 12,
        textAlign: 'center',
    },
    customAlertSubtitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 20,
        textAlign: 'center',
    },
    customAlertMessage: {
        fontSize: 15,
        color: '#6b7280',
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: 24,
    },
    reminderDetailsCard: {
        backgroundColor: '#f9fafb',
        borderRadius: 12,
        padding: 16,
        width: '100%',
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    reminderDetailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
        gap: 8,
    },
    reminderDetailLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#6b7280',
    },
    reminderDetailValue: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1f2937',
        flex: 1,
    },
    reminderPrepareText: {
        fontSize: 13,
        color: '#9ca3af',
        marginTop: 8,
        fontStyle: 'italic',
    },
    customAlertButton: {
        backgroundColor: '#9A8CFC',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 32,
        width: '100%',
        alignItems: 'center',
    },
    customAlertButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#ffffff',
    },
    customAlertButtonGroup: {
        flexDirection: 'row',
        gap: 12,
        width: '100%',
    },
    customAlertPrimaryButton: {
        backgroundColor: '#9A8CFC',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 24,
        flex: 1,
        alignItems: 'center',
    },
    customAlertPrimaryButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#ffffff',
    },
    customAlertSecondaryButton: {
        backgroundColor: '#f3f4f6',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 20,
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    customAlertSecondaryButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
    },

    // Payment Tab Styles
    amountCard: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    amountLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#6b7280',
        marginBottom: 8,
    },
    amountValue: {
        fontSize: 32,
        fontWeight: '700',
        color: '#1f2937',
        marginBottom: 12,
    },
    remainingText: {
        fontSize: 14,
        color: '#6b7280',
    },
    actionButtonsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        marginBottom: 24,
    },
    actionGridButton: {
        width: '22%',
        alignItems: 'center',
        gap: 8,
    },
    actionIcon: {
        width: 56,
        height: 56,
        borderRadius: 28,
        alignItems: 'center',
        justifyContent: 'center',
    },
    actionIconText: {
        fontSize: 24,
        color: '#3E3E3E',
    },
    actionLabel: {
        fontSize: 11,
        fontWeight: '500',
        color: '#3E3E3E',
        textAlign: 'center',
    },
    priceInputsRow: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 16,
    },
    priceInputGroup: {
        flex: 1,
    },
    priceInputLabel: {
        fontSize: 13,
        fontWeight: '600',
        color: '#3E3E3E',
        marginBottom: 8,
    },
    priceInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        paddingHorizontal: 12,
    },
    priceInput: {
        flex: 1,
        paddingVertical: 12,
        fontSize: 14,
        color: '#1f2937',
    },
    priceUnit: {
        fontSize: 13,
        fontWeight: '600',
        color: '#6b7280',
        marginLeft: 8,
    },
    completeButton: {
        backgroundColor: '#C4B5FD',
        borderRadius: 16,
        paddingVertical: 16,
        alignItems: 'center',
        marginTop: 24,
    },
    completeButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#ffffff',
    },
});

export default styles;
