import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
    mapViewContainer: {
        flex: 1,
        backgroundColor: '#f9fafb',
    },
    mapImage: {
        width: '100%',
        height: '100%',
        position: 'absolute',
        top: 0,
    },
    mapHeader: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: Platform.OS === 'ios' ? 60 : 50,
        paddingBottom: 16,
        backgroundColor: 'transparent',
    },
    mapCloseButton: {
        width: 40,
        height: 40,
        backgroundColor: 'white',
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    collapsedModalCard: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'white',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        padding: 20,
        paddingBottom: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 10,
    },
    propertiesScrollContent: {
        paddingHorizontal: 4,
        gap: 12,
    },
    propertyScrollCard: {
        width: 300,
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 14,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        borderWidth: 2,
        borderColor: '#e5e7eb',
        marginHorizontal: 6,
    },
    propertyScrollImageSmall: {
        width: 70,
        height: 70,
        borderRadius: 12,
        backgroundColor: '#f3f4f6',
    },
    propertyScrollInfo: {
        flex: 1,
        gap: 6,
    },
    propertyScrollTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#111827',
    },
    propertyScrollLocation: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    propertyScrollLocationText: {
        fontSize: 12,
        color: '#6b7280',
        flex: 1,
    },
    expandedModalCard: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'white',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        padding: 20,
        paddingBottom: 30,
    },
    backButton: {
        position: 'absolute',
        top: 20,
        left: 20,
        width: 36,
        height: 36,
        backgroundColor: '#f3f4f6',
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10,
    },
    handleBar: {
        width: 70,
        height: 5,
        backgroundColor: '#d1d5db',
        borderRadius: 2,
        alignSelf: 'center',
        marginBottom: 12,
    },
    propertiesToShowLabel: {
        fontSize: 20,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 23,
        textAlign: 'center',
    },
    scrollWrapper: {
        marginBottom: 20,
    },
    expandedPropertiesScroll: {
        paddingHorizontal: 0,
        gap: 10,
        marginBottom: 20,
    },
    expandedPropertyCard: {
        width: 310,
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 12,
        flexDirection: 'row',
        gap: 10,
        borderWidth: 2,
        borderColor: '#e5e7eb',
        marginHorizontal: 6,
    },
    expandedPropertyCardActive: {
        borderColor: '#bfb7fd',
        backgroundColor: '#faf9ff',
    },
    expandedPropertyCardImage: {
        width: 70,
        height: 70,
        borderRadius: 12,
        backgroundColor: '#f3f4f6',
    },
    expandedPropertyCardInfo: {
        flex: 1,
        justifyContent: 'center',
        gap: 2,
    },
    propertyCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 8,
    },
    expandedPropertyCardTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#111827',
        flex: 1,
    },
    expandedPropertyCardLocation: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    expandedPropertyCardLocationText: {
        fontSize: 13,
        color: '#313131',
        flex: 1,
    },
    propertyPrice: {
        fontSize: 14,
        fontWeight: '700',
        color: '#9f95f2',
        marginTop: 2,
    },
    feedbackButtonsRow: {
        flexDirection: 'row',
        backgroundColor: 'white',
        borderRadius: 13,
        borderWidth: 1.5,
        borderColor: '#e5e7eb',
        overflow: 'hidden',
        marginBottom: 16,
        alignItems: 'center',
    },
    feedbackBtn: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        paddingVertical: 18,
    },
    verticalDivider: {
        width: 1.5,
        height: '60%',
        backgroundColor: '#e5e7eb',
    },
    feedbackTextHorizontal: {
        fontSize: 12,
        fontWeight: '600',
        color: '#374151',
    },
    contactOwnerButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: 'white',
        paddingVertical: 14,
        borderRadius: 12,
        marginBottom: 12,
        borderWidth: 1.5,
        borderColor: '#d1d5db',
    },
    contactOwnerText: {
        fontSize: 15,
        fontWeight: '700',
        color: '#374151',
    },
    navigateButtonExpanded: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#a9a0f5',
        paddingVertical: 16,
        borderRadius: 14,
    },
    navigateButtonExpandedText: {
        fontSize: 16,
        fontWeight: '700',
        color: 'white',
    },
});

export default styles;
